// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhrRfRiL-k3NNg2UdB1ad6e5_nPRPNtcI',
    appId: '1:983419112932:web:313a2a876a51c87f40cbf1',
    messagingSenderId: '983419112932',
    projectId: 'mind-aiyori',
    authDomain: 'mind-aiyori.firebaseapp.com',
    storageBucket: 'mind-aiyori.firebasestorage.app',
    measurementId: 'G-NL5SGPEFPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBltqYUGX4xB_5Jeny7SKEvn85d4uBQKiY',
    appId: '1:983419112932:android:d4f30bbe3a54a56040cbf1',
    messagingSenderId: '983419112932',
    projectId: 'mind-aiyori',
    storageBucket: 'mind-aiyori.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHS0aJz16RDgamg-3M5-W4iAHRL6uJZds',
    appId: '1:983419112932:ios:fadc93a8eb69ee8640cbf1',
    messagingSenderId: '983419112932',
    projectId: 'mind-aiyori',
    storageBucket: 'mind-aiyori.firebasestorage.app',
    iosBundleId: 'com.example.aiyori',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHS0aJz16RDgamg-3M5-W4iAHRL6uJZds',
    appId: '1:983419112932:ios:fadc93a8eb69ee8640cbf1',
    messagingSenderId: '983419112932',
    projectId: 'mind-aiyori',
    storageBucket: 'mind-aiyori.firebasestorage.app',
    iosBundleId: 'com.example.aiyori',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhrRfRiL-k3NNg2UdB1ad6e5_nPRPNtcI',
    appId: '1:983419112932:web:9e403853f98f244f40cbf1',
    messagingSenderId: '983419112932',
    projectId: 'mind-aiyori',
    authDomain: 'mind-aiyori.firebaseapp.com',
    storageBucket: 'mind-aiyori.firebasestorage.app',
    measurementId: 'G-X7LC1LM521',
  );
}
