// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGdG8OqjPDMLHuUrzBEb-uSD6r3Op51Us',
    appId: '1:96272943359:web:3b44bd1366d584b52424ca',
    messagingSenderId: '96272943359',
    projectId: 'aiyori-aa',
    authDomain: 'aiyori-aa.firebaseapp.com',
    storageBucket: 'aiyori-aa.firebasestorage.app',
    measurementId: 'G-H1B5HKLNR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZKK8mLDrCoyN-gYbWkUhLeT83UWurHTA',
    appId: '1:96272943359:android:bbad0477679df4ed2424ca',
    messagingSenderId: '96272943359',
    projectId: 'aiyori-aa',
    storageBucket: 'aiyori-aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHG9huDRD3fanoGdZ1FMNLou20PFTmN6w',
    appId: '1:96272943359:ios:e942f9634bf32d412424ca',
    messagingSenderId: '96272943359',
    projectId: 'aiyori-aa',
    storageBucket: 'aiyori-aa.firebasestorage.app',
    iosBundleId: 'com.example.aiyori',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHG9huDRD3fanoGdZ1FMNLou20PFTmN6w',
    appId: '1:96272943359:ios:e942f9634bf32d412424ca',
    messagingSenderId: '96272943359',
    projectId: 'aiyori-aa',
    storageBucket: 'aiyori-aa.firebasestorage.app',
    iosBundleId: 'com.example.aiyori',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhrRfRiL-k3NNg2UdB1ad6e5_nPRPNtcI',
    appId: '1:983419112932:web:9e403853f98f244f40cbf1',
    messagingSenderId: '983419112932',
    projectId: 'mind-aiyori',
    authDomain: 'mind-aiyori.firebaseapp.com',
    storageBucket: 'mind-aiyori.firebasestorage.app',
    measurementId: 'G-X7LC1LM521',
  );
}